// actionTypes.js
export const FETCH_CLOTHES_REQUEST = "FETCH_CLOTHES_REQUEST";
export const FETCH_CLOTHES_SUCCESS = "FETCH_CLOTHES_SUCCESS";
export const FETCH_CLOTHES_FAILURE = "FETCH_CLOTHES_FAILURE";
